// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kPw3136n_oYPMViVCswSmLk_16ZEEJU',
    appId: '1:149224672621:web:b539ed9656707ba0e01e64',
    messagingSenderId: '149224672621',
    projectId: 'list-firebase-8c37b',
    authDomain: 'list-firebase-8c37b.firebaseapp.com',
    storageBucket: 'list-firebase-8c37b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9zxcKl7jxjn7ojzhP68e2KZsLSOCtCo',
    appId: '1:149224672621:android:5a4e4e97a4327d78e01e64',
    messagingSenderId: '149224672621',
    projectId: 'list-firebase-8c37b',
    storageBucket: 'list-firebase-8c37b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcXYfAckBhQjlC9Rq-LpCO0LBt7WFuzG8',
    appId: '1:149224672621:ios:0f066c6065f1c37be01e64',
    messagingSenderId: '149224672621',
    projectId: 'list-firebase-8c37b',
    storageBucket: 'list-firebase-8c37b.appspot.com',
    iosClientId: '149224672621-galugm72q40bf0it143vm13v3r5m4bq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIlmuTajwid',
  );
}
